language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm i -g angular-cli-ghpages

script:
  - ng build --prod --base-href "https://joshilewis.github.io/lendtome-ng4/"
  - ngh --no-silent

after_success:

notifications:
  email:
    on_failure: change
    on_success: change
